version: '3.8'

services:

  # db:
  #     image: mysql:8.0
  #     command: --default-authentication-plugin=mysql_native_password 
  #     ports: 
  #       - "3306:3306"
  #     environment:
  #       MYSQL_DATABASE: hw1
  #       MYSQL_USER: user
  #       MYSQL_PASSWORD: user
  #       MYSQL_ROOT_PASSWORD: user
  #     volumes:
  #       - datafiles:/var/lib/mysql
  #     restart: always
  #     cap_add:
  #       - SYS_NICE  # CAP_SYS_NICE
  #     healthcheck:
  #       test: "mysql hw1 -uuser -puser -e 'SELECT 1;'"
  #       interval: 20s
  #       timeout: 10s
  #       retries: 2

  hw1:
  #  depends_on:
  #     db:
  #       condition: service_healthy
    build: ./hw1-app
    container_name: hw1-app
    restart: on-failure
    ports:
      - 8080:8080
    healthcheck:
      test: "curl http://localhost:8000"
      interval: 20s
      timeout: 10s
      retries: 2

  # client:
  #   build: ./web-app
  #   ports:
  #       - "8000:8080"
  #   restart: on-failure
  #   # volumes:
  #   #     - ./src:/etc/share/nginx/html
  #   #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on: 
  #       - backend