version: '3.8'

services:

  spring:
    build: ./hw1-app
    container_name: hw1-app
    restart: unless-stopped
    image: hw1-app
    ports:
      - 8080:8080

  angular:
      build: ./web-application
      container_name: hw1-angular
      environment: 
        - API_BASE_URL=http://spring:8080/api/
      restart: unless-stopped
      ports:
          - 80:80